name: ecommerce_admin_tut
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  responsive_builder: ^0.7.0
  get_it: ^8.0.3
  fl_chart: ^0.70.2
  charts_flutter: ^0.12.0
  provider: ^6.1.2
  responsive_table: ^0.2.0+2
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.2
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.1
  flutter_spinkit: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/products.png
